name: www.threefold_io
on: 
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on www.threefold.io
      uses: appleboy/ssh-action@master
      with:
        host: www.threefold.io
        username: root
        key: ${{ secrets.TF_SECRET }}
        port: 22
        script: |
          cd /opt/www_threefold_io/
          git log -1
          git fetch
          git reset --hard origin/master
          sed -i "s/https:\/\/dev.threefold.io/https:\/\/www.threefold.io/g" config.toml
          ./build.sh
          
  wait:
    needs: deploy
    name: Wait for Website Update
    runs-on: ubuntu-latest
    steps:
    - name: Wait Period
      id: wait-deploy
      run: |
        echo "Sleeping for 30"
        sleep 30
        
  checklinks:
    needs: wait
    name: Check for Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Check for Broken Links
        id: link-report
        uses: docker://ghcr.io/threefoldfoundation/website-link-checker:latest
        with:
          args: 'https://www.threefold.io -w 404'