name: www3.threefold_io
on: 
  push:
    branches: [ 3.10.0 ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on www3.threefold.io
      uses: appleboy/ssh-action@master
      with:
        host: www3.threefold.io
        username: webuser
        key: ${{ secrets.TF_SECRET }}
        port: 34022
        script: |
          cd websites/www3/www_threefold_io/
          git log -1
          git restore .
          git pull
          sed -i "s/https:\/\/www.threefold.io/https:\/\/www3.threefold.io/g" config.toml
          bash build.sh
          
  wait:
    needs: deploy
    name: Wait for Website Update
    runs-on: ubuntu-latest
    steps:
    - name: Wait Period
      id: wait-deploy
      run: |
        echo "Sleeping for 30"
        sleep 30
        
  checklinks:
    needs: wait
    name: Check for Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Check for Broken Links
        id: link-report
        uses: docker://ghcr.io/threefoldfoundation/website-link-checker:latest
        with:
          args: 'https://www3.threefold.io -w 404'